### ISSUE TITLE
remove "kubernetes.io/arch: amd64" nodeselector in yaml of demo applications

### ISSUE THREAD

**Issue by ethinx** [flomesh-io/osm-edge-docs#76]
As subject, the book* applications and curl has arm64 image on dockerhub now, we could remove the selector.

* curlimages/curl:latest
* openservicemesh/bookbuyer:latest-main
* openservicemesh/bookstore:latest-main
* openservicemesh/bookthief:latest-main
* openservicemesh/bookwarehouse:latest-main

**Comment by naqvis** [comment]
Fixed this in latest deployment.
